const ADDRESSES = {
  // hardhat chain
  31337: {
    ADDRESS_SUPERFLUID_RESOLVER: `${process.env.REACT_APP_LOCAL_ADDRESS_SUPERFLUID_RESOLVER}`,
    ADDRESS_SUPERFLUID_HOST: `${process.env.REACT_APP_LOCAL_ADDRESS_SUPERFLUID_HOST}`,
    ADDRESS_SUPERFLUID_CFA: `${process.env.REACT_APP_LOCAL_ADDRESS_SUPERFLUID_CFA}`,
    ADDRESS_SUPERFLUID_IDA: `${process.env.REACT_APP_LOCAL_ADDRESS_SUPERFLUID_IDA}`,

    ADDRESS_DCA_SUPERAPP: `${process.env.REACT_APP_LOCAL_ADDRESS_DCA_SUPERAPP}`,

    ADDRESS_FDAI: `${process.env.REACT_APP_LOCAL_ADDRESS_FDAI}`,
    ADDRESS_FDAIX: `${process.env.REACT_APP_LOCAL_ADDRESS_FDAIX}`,
    ADDRESS_ETHG: `${process.env.REACT_APP_LOCAL_ADDRESS_ETHG}`,
    ADDRESS_ETHGX: `${process.env.REACT_APP_LOCAL_ADDRESS_ETHGX}`,
  },
  // polygon mumbai
  80001: {
    ADDRESS_SUPERFLUID_RESOLVER: `${process.env.REACT_APP_MUMBAI_ADDRESS_SUPERFLUID_RESOLVER}`,
    ADDRESS_SUPERFLUID_HOST: `${process.env.REACT_APP_MUMBAI_ADDRESS_SUPERFLUID_HOST}`,
    ADDRESS_SUPERFLUID_CFA: `${process.env.REACT_APP_MUMBAI_ADDRESS_SUPERFLUID_CFA}`,
    ADDRESS_SUPERFLUID_IDA: `${process.env.REACT_APP_MUMBAI_ADDRESS_SUPERFLUID_IDA}`,

    // ADDRESS_DCA_FDAIX_ETHGX: `${process.env.REACT_APP_MUMBAI_ADDRESS_DCA_FDAI_ETHGX}`,
    ADDRESS_DCA_FDAIX_ENCX: `${process.env.REACT_APP_MUMBAI_ADDRESS_DCA_FDAIX_ENCX}`,
    ADDRESS_DCA_FDAIX_BTFDCAX: `${process.env.REACT_APP_MUMBAI_ADDRESS_DCA_FDAIX_BTFDCAX}`,

    ADDRESS_FDAI: `${process.env.REACT_APP_MUMBAI_ADDRESS_FDAI}`,
    ADDRESS_FDAIX: `${process.env.REACT_APP_MUMBAI_ADDRESS_FDAIX}`,
    // ADDRESS_ETHG: `${process.env.REACT_APP_MUMBAI_ADDRESS_ETHG}`,
    // ADDRESS_ETHGX: `${process.env.REACT_APP_MUMBAI_ADDRESS_ETHGX}`,

    ADDRESS_ENC: `${process.env.REACT_APP_MUMBAI_ADDRESS_ENC}`,
    ADDRESS_ENCX: `${process.env.REACT_APP_MUMBAI_ADDRESS_ENCX}`,
    ADDRESS_BTFDCA: `${process.env.REACT_APP_MUMBAI_ADDRESS_BTFDCA}`,
    ADDRESS_BTFDCAX: `${process.env.REACT_APP_MUMBAI_ADDRESS_BTFDCAX}`,
  },
};

const SF_DISTRIBUTION_SUBSCRIPTION_IDX = `${process.env.REACT_APP_DISTRIBUTION_IDX}`;

export { ADDRESSES, SF_DISTRIBUTION_SUBSCRIPTION_IDX };
